#!/bin/sh
#this script is released under the MIT Public License

help(){
  cat <<EOF
usage: `basename $0` [-h] <new/script/path>

this script initialize a new script
arguments:
   <new/script/path>: the path to the new script
options:
   -h Prints this help message

EOF
  exit 1
}

init_skel(){
cat >$NEW_SCRIPT_PATH <<EOF
#!/bin/sh

help(){
  cat <<EOF
usage: \`basename \$0\` [-h] <args>

<description>

arguments:
  <args>
options:
  -h Prints this help message
%EOF
  exit 1
}

while getopts ":hn:" opt; do
  case \$opt in
    h)  help;;
    n)  NAME="\$OPTARG";;
    \?) echo "Invalid option: -\$OPTARG" >&2; help;;
    :)  echo "Option -\$OPTARG requires an argument." >&2; help;;
  esac
done

shift \$(( \$OPTIND-1 ))

exit 0
EOF
sed -i "s/%EOF/EOF/" $NEW_SCRIPT_PATH
chmod 755 $NEW_SCRIPT_PATH
}

while getopts ":hn:" opt; do
  case $opt in
    h)  help;;
    \?) echo "Invalid option: -$OPTARG" >&2; help;;
    :)  echo "Option -$OPTARG requires an argument." >&2; help;;
  esac
done

shift $(( $OPTIND-1 ))

NEW_SCRIPT_PATH="$1"

if [ -z "$NEW_SCRIPT_PATH" ]
then
  echo "The path of the script is mandatory."
  help
fi

init_skel

exit 0
